beta_project/urls.py
"""
beta_project URL Configuration.
"""

from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('cinema/', include('cinema.urls')),
    path('admin/', admin.site.urls),
    path('insane/', include('insane_app.urls')),
    path('rent-cars/', include('rent_cars.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

cinema/urls.py
from django.urls import path
from .apps import CinemaConfig
from .views import (ProductListView, ProductDetailView, NewsListView,
                    NewsDetailView, FilmDetailView, CinemaPersonDetailView,
                    FilmListView, TopRatedProductListView,
                    NewReleasesProductListView, CelebrityNewsListView,
                    TopRatedFilmListView, BudgetFilmListView,
                    UsaGrossFilmListView, WorldGrossFilmListView,
                    SearchResultsView, YearFilmListView, GenreFilmListView,
                    CountryFilmListView, LanguageFilmListView, MpaaFilmListView,
                    DistributorFilmListView, IndexListView)


app_name = CinemaConfig.name

urlpatterns = [
    path('', IndexListView.as_view(), name='index-list'),
    path('blu-ray/', ProductListView.as_view(), name='product-list'),
    path('film/', FilmListView.as_view(), name='film-list'),
    path('news/', NewsListView.as_view(), name='news-list'),
    path('search/', SearchResultsView.as_view(), name='search_results'),
    path('blu-ray/top-rated/', TopRatedProductListView.as_view(),
         name='top-rated-product-list'),
    path('blu-ray/new-releases/', NewReleasesProductListView.as_view(),
         name='new-releases-product-list'),
    path('film/top-rated/', TopRatedFilmListView.as_view(),
         name='top-rated-film-list'),
    path('film/budget/', BudgetFilmListView.as_view(),
         name='budget-film-list'),
    path('film/usa-gross/', UsaGrossFilmListView.as_view(),
         name='usa-gross-film-list'),
    path('film/world-gross/', WorldGrossFilmListView.as_view(),
         name='world-gross-film-list'),
    path('news/celebrity/', CelebrityNewsListView.as_view(),
         name='celebrity-news-list'),
    path('blu-ray/<int:pk>/', ProductDetailView.as_view(),
         name='product-detail'),
    path('film/<int:pk>/', FilmDetailView.as_view(),
         name='film-detail'),
    path('movie-person/<int:pk>/', CinemaPersonDetailView.as_view(),
         name='movie-person-detail'),
    path('news/<int:pk>/', NewsDetailView.as_view(),
         name='news-detail'),
    path('film/year/<int:year>/', YearFilmListView.as_view(),
         name='year-film-list'),
    path('film/genre/<str:genre>/', GenreFilmListView.as_view(),
         name='genre-film-list'),
    path('film/country/<str:country>/', CountryFilmListView.as_view(),
         name='country-film-list'),
    path('film/language/<str:language>/', LanguageFilmListView.as_view(),
         name='language-film-list'),
    path('film/mpaa/<int:pk>/', MpaaFilmListView.as_view(),
         name='mpaa-film-list'),
    path('film/distributor/<str:distributor>/',
         DistributorFilmListView.as_view(), name='distributor-film-list'),
]

cinema/models.py
from datetime import date, timedelta
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()

GENDER_CHOICES = (
    ("M", "Male"),
    ("F", "Female"),
)


def upload_to_film(instance, filename):
    return "films/{}_{}.jpg".format(instance.title, instance.pk)


def upload_to_cinema_person(instance, filename):
    return "cinema_persons/{}_{}_{}.jpg".format(
        instance.user.first_name, instance.user.last_name, instance.pk
    )


def upload_photo_to_news_feed(instance, filename):
    return "cinema_news_feed/{}_{}.jpg".format(instance.title, instance.pk)


def upload_photo_to_news_detail(instance, filename):
    return "cinema_news_detail/{}_{}.jpg".format(instance.title, instance.pk)


class ExtendedProfileMixin(models.Model):
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, default="M")
    country = models.ForeignKey(
        "Country", on_delete=models.SET_NULL, blank=True, null=True
    )
    birthday = models.DateField(null=True, blank=True)

    class Meta:
        abstract = True


class DateMixin(models.Model):
    created_at = models.DateTimeField(auto_created=True)

    class Meta:
        abstract = True


class Country(models.Model):
    name = models.CharField(max_length=64, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "countries"
        ordering = ["name"]


class Genre(models.Model):
    name = models.CharField(max_length=16, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["name"]


class ImdbRating(models.Model):
    value = models.DecimalField(max_digits=2, decimal_places=1, unique=True)

    def __str__(self):
        return str(self.value)

    class Meta:
        ordering = ["value"]


class MpaaRating(models.Model):
    value = models.CharField(max_length=10, unique=True)
    description = models.CharField(max_length=512, unique=True)

    def __str__(self):
        return str(self.value)

    class Meta:
        ordering = ["value"]


class Language(models.Model):
    name = models.CharField(max_length=16, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["name"]


class Distributor(models.Model):
    name = models.CharField(max_length=32, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["name"]


class CinemaPerson(ExtendedProfileMixin):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(unique=True)
    oscar_awards = models.PositiveSmallIntegerField(default=0)
    avatar = models.ImageField(upload_to=upload_to_cinema_person, blank=True,
                               null=True)

    @property
    def age(self):
        if self.birthday:
            return (date.today() - self.birthday) // timedelta(days=365.2425)
        return None

    @property
    def fullname(self):
        return f"{self.user.first_name} {self.user.last_name}"

    def __str__(self):
        return self.fullname

    class Meta:
        ordering = ["user__first_name", "user__last_name"]


class Film(models.Model):
    title = models.CharField(max_length=64)
    country = models.ManyToManyField(Country)
    genre = models.ManyToManyField(Genre)
    staff = models.ManyToManyField(CinemaPerson,
                                   through="CinemaFilmPersonProfession")
    budget = models.PositiveIntegerField(null=True, blank=True)
    usa_gross = models.BigIntegerField(default=0)
    world_gross = models.BigIntegerField(default=0)
    run_time = models.DurationField()
    description = models.TextField(unique=True)
    release_data = models.DateField()
    language = models.ManyToManyField(Language)
    distributor = models.ManyToManyField(Distributor)
    imdb_rating = models.ForeignKey(
        ImdbRating, on_delete=models.SET_NULL, blank=True, null=True
    )
    mpaa_rating = models.ForeignKey(
        MpaaRating, on_delete=models.SET_NULL, blank=True, null=True
    )
    oscar_awards = models.PositiveSmallIntegerField(default=0)
    poster = models.ImageField(upload_to=upload_to_film, blank=True, null=True)

    def __str__(self):
        return self.title

    @property
    def year(self):
        return self.release_data.year

    class Meta:
        ordering = ["title"]


class CinemaProfession(models.Model):
    name = models.CharField(max_length=16, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["pk"]


class CinemaFilmPersonProfession(models.Model):
    cinema_person = models.ForeignKey(CinemaPerson, on_delete=models.CASCADE)
    film = models.ForeignKey(Film, on_delete=models.CASCADE)
    profession = models.ForeignKey(CinemaProfession, on_delete=models.CASCADE)

    def __str__(self):
        return (
            f"{self.film.title}: {self.profession.name} - "
            f"{self.cinema_person.fullname}"
        )

    class Meta:
        verbose_name = "cinema film person profession"
        verbose_name_plural = "Cinema films persons professions"
        ordering = ["film__title", "profession",
                    "cinema_person__user__first_name"]


class News(DateMixin):
    title = models.CharField(max_length=128, unique=True)
    description = models.TextField(unique=True)
    news_source = models.CharField(max_length=32)
    news_author = models.CharField(max_length=64, default="", blank=True)
    film = models.ManyToManyField(Film, blank=True)
    cinema_person = models.ManyToManyField(CinemaPerson, blank=True)
    news_feed_photo = models.ImageField(
        upload_to=upload_photo_to_news_feed, blank=True, null=True
    )
    news_detail_photo = models.ImageField(
        upload_to=upload_photo_to_news_detail, blank=True, null=True
    )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = "news"
        ordering = ["-created_at"]


class Product(DateMixin):
    price = models.DecimalField(max_digits=5, decimal_places=2)
    in_stock = models.PositiveSmallIntegerField(default=0)
    film = models.OneToOneField(Film, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.film.title} [Blu-ray]"

    class Meta:
        ordering = ["-film__oscar_awards", ]

insane_app/models.py
from django.db import models
from django.db.models import F
from django.contrib.auth.models import User
from django.db.models.signals import pre_delete, post_save
from django.dispatch import receiver
from django.contrib.auth import get_user_model
from django.urls import reverse
from django.utils.html import escape

User = get_user_model()


class SanityRank(models.Model):
    name = models.CharField(unique=True, max_length=20)
    sanity_cap = models.PositiveIntegerField()

    def __str__(self):
        return self.name


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    _sanity = models.PositiveIntegerField(default=0)
    rank = models.ForeignKey(SanityRank, on_delete=models.PROTECT)

    @property
    def sanity(self):
        return self._sanity

    @sanity.setter
    def sanity(self, value):
        if value <= self.rank.sanity_cap:
            self._sanity = value
        else:
            self._sanity = self.rank.sanity_cap

    # FIXME: this code breaks the program for everyone else
    # @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            rank = SanityRank.objects.first()
            Profile.objects.create(user=instance, sanity=rank.sanity_cap, rank=rank)

    # FIXME: this code breaks the program for everyone else
    # @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        instance.profile.save()

    class Meta:
        ordering = ['user']
        db_table = 'insane_user'

    def __str__(self):
        return self.user.username


class UserGroup(models.Model):
    name = models.CharField(max_length=32)

    def get_new_admin(self):
        return self.members.first()

    members = models.ManyToManyField(
        User,
        related_name='user_group',
        through='Membership',
        through_fields = ('user_group', 'user')
    )
    dt_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    def add_member(self, new_user):
        Membership.objects.create(user = new_user, user_group=self)


class Membership(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    user_group = models.ForeignKey(UserGroup, on_delete=models.CASCADE)
    ROLES = (
        ('ad', 'admin'),
        ('mb', 'member'),
    )
    role = models.CharField(max_length=2, choices=ROLES)

    class Meta:
        unique_together = (('user', 'user_group'),)

    def __str__(self):
        return f'{self.user_group.name} - {self.user.username}[{self.get_role_display()}]'


class Story(models.Model):
    name = models.CharField(max_length=64)
    body = models.TextField(max_length=600)
    like_count = models.PositiveIntegerField(default=0, blank=True)
    dt_created = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True
    )

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('insane:story', args=[self.pk])


def get_story_image (instance, filename):
    return f"images/{instance.author.username}/{filename}"


class StoryImage(models.Model):
    image = models.ImageField(upload_to=get_story_image)
    product = models.ForeignKey(
        Story,
        related_name='image',
        on_delete=models.CASCADE
    )


class StoryLike(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    story = models.ForeignKey(Story, on_delete=models.CASCADE)

    class Meta:
        unique_together = (("user", "story"),)

    def __str__(self):
        return f"{self.user.username} likes {self.story.name}"


@receiver(post_save, sender=StoryLike)
def _story_like_save(sender, instance, **kwargs):
    Story.objects.filter(pk=instance.story.pk).update(like_count=F('like_count')+1)

@receiver(pre_delete, sender=StoryLike)
def _story_like_delete(sender, instance, **kwargs):
    Story.objects.filter(pk=instance.story.pk).update(like_count=F('like_count')-1)


class Category(models.Model):
    name = models.CharField(unique=True, max_length=20)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=64)
    description = models.TextField(max_length=500)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    story = models.ForeignKey(
        Story,
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )
    dt_created = models.DateTimeField(auto_now_add=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    categories = models.ManyToManyField(Category)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('insane:product', args=[self.pk])


# ProductImage
def get_product_image(instance, filename):
    return f"images/{instance.product.owner.username}/{filename}"


class ProductImage(models.Model):
    image = models.ImageField(upload_to=get_product_image)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    class Meta:
        unique_together = (('image', 'product'),)

    def __str__(self):
        return f"{self.product.name}, {self.image}"

    def image_tag(self):
        return f'<img src="/static/{self.image}"/>'

    image_tag.short_description = 'Image'
    image_tag.allow_tags = True

cinema/templates/cinema/base_cinema_detail.html
{% extends 'cinema/base.html' %}

{% block description %}{% endblock description %}


{% block title %}{% endblock title %}


{% block main_content %}

<div class="row">
  <div class="col-md-4 detail_photo align-self-center">

    {% block page_photo %}{% endblock %}

  </div>
  <div class="col-md-6 detail_main_info align-self-center">
    <h4 class="detail_main_info_title mb-4 pl-2">{% block page_name %}{% endblock %}</h4>

    {% block page_main_info %}{% endblock %}

  </div>
  <div class="col-md-2 mb-4 align-self-end">

    {% block page_oscar_price %}{% endblock %}

  </div>
</div>
<div class="row mt-2">
  <div class="col-md-12">
    <a class="detail_extra_heading pl-2"
       href="javascript:collapsElement('1001')"
       title=""
       rel="nofollow">Overview &#9660
    </a>
    <div class="pt-3 pr-5"
         id="1001"
         style="display: True">
      <table class="table table-responsive">
        <tbody>
        <tr class="align-top">
          <th scope="col">{% block page_overview_title %}{% endblock %}</th>
          <td>
            <p class="text-justify">

            {% block page_overview_description %}{% endblock %}

            </p>
          </td>
        </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

{% block page_extra_info %}{% endblock %}


{% block page_box_office %}{% endblock %}


{% block page_related_news %}{% endblock %}

<script>
  function collapsElement(id) {
  if ( document.getElementById(id).style.display != "none" ) {
  document.getElementById(id).style.display = 'none';
  }
  else {
  document.getElementById(id).style.display = '';
  }
  }
</script>

{% endblock main_content %}

cinema/templates/cinema/cinema_person_detail.html
{% extends 'cinema/base_cinema_detail.html' %}

{% load get_text_hyperlinks_filter %}

{% block description %}{{ cinema_person.fullname }}{% endblock %}


{% block title %}{{ cinema_person.fullname }}{% endblock %}


{% block page_photo %}
{% include "cinema/includes/inc_cinema_photo.html" with poster=cinema_person.avatar name=cinema_person.fullname %}
{% endblock page_photo %}


{% block page_name %}{{ cinema_person.fullname }}{% endblock %}


{% block page_main_info %}

<table class="table table-responsive table-striped">
  <tbody class="align-top">
  <tr>
    <th scope="col">Gender:</th>
    <td>{{ cinema_person.get_gender_display }}</td>
  </tr>
  <tr>
    <th scope="col">Age:</th>
    <td>{{ cinema_person.age }}</td>
  </tr>
  <tr>
    <th scope="col">Birthday:</th>
    <td>{{ cinema_person.birthday|date:"j M Y" }}</td>
  </tr>
  <tr>
    <th scope="col">Country:</th>
    <td>
      <a href="{% url 'cinema:country-film-list' cinema_person.country %}">
        {{ cinema_person.country }}
      </a>
    </td>
  </tr>
  <tr>
    <th scope="col">Career:</th>
    <td>

      {% for profession in person_professions %}

      {{ profession }}{% if not forloop.last %},{% endif %}

      {% endfor %}

    </td>
  </tr>
  <tr>
    <th scope="col">Genre{{ genres|pluralize:"s" }}:</th>
    <td>

      {% for genre in genres %}

      <a href="{% url 'cinema:genre-film-list' genre %}">{{ genre }}</a>
      {% if not forloop.last %},{% endif %}

      {% endfor %}

    </td>
  </tr>
  <tr>
    <th scope="col">Mov{{ number_of_films|pluralize:"y,ies" }}:</th>
    <td>{{ number_of_films }}</td>
  </tr>
  <tr>
    <th scope="col">Years:</th>
    <td>{{ years_of_films }}</td>
  </tr>

  </tbody>
</table>

{% endblock page_main_info %}


{% block page_oscar_price %}
{% include "cinema/includes/inc_cinema_oscar.html" with cinema=cinema_person %}
{% endblock page_oscar_price %}


{% block page_overview_title %}Biography:{% endblock %}


{% block page_overview_description %}{{ cinema_person.bio|get_text_hyperlinks|safe }}{% endblock %}


{% block page_extra_info %}

<div class="row mt-2">
  <div class="col-md-12">
    <p class="detail_extra_heading pl-2">Filmography</p>
    <div class="row d-flex justify-content-center">

      {% for profession, films in filmography.items %}

      <p class="font-weight-bold">{{ profession }}</p>
      <table class="table table-responsive table-striped d-flex justify-content-center">
        <tbody>

        {% for film in films %}

        <tr>
          <td class="align-middle">

            {{ forloop.counter }}.

          </td>
          <td class="align-middle" width=560px">
            <a href="{% url 'cinema:film-detail' film.pk %}">

              {{ film.title }} ({{ film.release_data__year }})

            </a>
          </td>
          <td class="align-middle">

            {{ film.imdb_rating__value }}

          </td>
        </tr>

        {% endfor %}

        </tbody>
      </table>

      {% endfor %}

    </div>
  </div>
</div>

{% endblock page_extra_info %}


{% block page_related_news %}
{% include "cinema/includes/inc_cinema_related_news.html" %}
{% endblock page_related_news %}

cinema/templates/cinema/film_detail.html
{% extends 'cinema/base_cinema_detail.html' %}

{% load get_text_hyperlinks_filter %}

{% block description %}{{ film.title }}{% endblock %}


{% block title %}{{ film.title }}{% endblock %}


{% block page_photo %}
{% include "cinema/includes/inc_cinema_photo.html" with poster=film.poster name=film.title %}
{% endblock page_photo %}


{% block page_name %}{{ film.title }}{% endblock %}


{% block page_main_info %}
{% include "cinema/includes/inc_cinema_main_info.html" with cinema=film %}
{% include "cinema/includes/inc_cinema_imdb.html" with cinema=film %}
{% endblock page_main_info %}


{% block page_oscar_price %}
{% include "cinema/includes/inc_cinema_oscar.html" with cinema=film %}
{% endblock page_oscar_price %}


{% block page_overview_title %}Storyline:{% endblock %}


{% block page_overview_description %}{{ film.description|get_text_hyperlinks|safe }}{% endblock %}


{% block page_extra_info %}
{% include "cinema/includes/inc_cinema_extra_info.html" with cinema=film %}
{% endblock page_extra_info %}


{% block page_box_office %}
{% include "cinema/includes/inc_cinema_box_office.html" with cinema=film %}
{% endblock page_box_office %}


{% block page_related_news %}

{% if related_news %}

{% include "cinema/includes/inc_cinema_related_news.html" with cinema=related_news %}

{% endif %}

{% endblock page_related_news %}

cinema/templates/cinema/index_list.html
{% extends 'cinema/base.html' %}

{% block description %}{{ page_title }}{% endblock description %}


{% block title %}{{ page_title }}{% endblock title %}


{% block main_content %}

{% include "cinema/includes/inc_index_title.html" with title=title_news description=description_news %}

<div class="row">
  <div class="col-12 pb-0">
    <!--SECTION START-->
    <section class="row">
      <!--Start slider news-->
      <div class="col-12 col-md-6 pb-0 pb-md-3 pt-2 pr-md-1 pl-md-1">
        <div id="featured" class="carousel slide carousel" data-ride="carousel">
          <!--dots navigate-->
          <ol class="carousel-indicators top-indicator">
            <li data-target="#featured" data-slide-to="0" class="active"></li>
            <li data-target="#featured" data-slide-to="1"></li>
            <li data-target="#featured" data-slide-to="2"></li>
            <li data-target="#featured" data-slide-to="3"></li>
            <li data-target="#featured" data-slide-to="4"></li>
          </ol>
          <!--carousel inner-->
          <div class="carousel-inner">

            {% include "cinema/includes/inc_index_news_slider.html" %}

          </div>
          <!--end carousel inner-->
        </div>

        <!--navigation-->
        <a class="carousel-control-prev" href="#featured" role="button"
           data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#featured" role="button"
           data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
      <!--End slider news-->

      <!--Start box news-->
      <div class="col-12 col-md-6 pt-2 mb-3 mb-lg-4">
        <div class="row">

          {% for news in news_list|slice:"7:11" %}

          <!--news box-->
          <div class="col-6 pb-1 pt-0 px-1">
            <div class="card border-0 rounded-0 text-white overflow zoom">
              <div class="position-relative">
                <!--thumbnail img-->
                <div class="ratio_right-cover-2 image-wrapper">
                  <a href="{% url 'cinema:news-detail' news.pk %}">
                    <img class="img-fluid"
                         src="{{ news.news_detail_photo.url }}"
                         alt="{{ news.title }} picture"
                         title="{{ news.title }}">
                  </a>
                </div>
                <div class="position-absolute px-1 px-lg-2 py-1 py-lg-2 b-0 w-100 bg-shadow">
                  <!--title-->
                  <a href="{% url 'cinema:news-detail' news.pk %}">
                    <h6 class="text-white my-0">{{ news.title }}</h6>
                  </a>
                </div>
              </div>
            </div>
          </div>
          <!--end news box-->

          {% endfor %}

        </div>
      </div>
      <!--End box news-->
    </section>
    <!--END SECTION-->
  </div>
</div>

{% include "cinema/includes/inc_index_title.html" with title=title_blu_ray description=description_blu_ray %}

<div class="row pb-3">
  <div class="col-12">
    <h4><b>{{ title_top_rated }}</b></h4>
  </div>
</div>
<div class="row">
  <div class="col-12 pb-4 px-0">
    <div class="MultiCarousel" data-items="1,3,5,6" data-slide="1" id="MultiCarousel"
         data-interval="1000">
      <div class="MultiCarousel-inner">

      {% include "cinema/includes/inc_index_product_slider.html" with product_list=top_rated_list %}

      </div>
      <button class="btn btn-primary leftLst"><</button>
      <button class="btn btn-primary rightLst">></button>
    </div>
  </div>
</div>
<div class="row pb-3">
  <div class="col-12">
    <h4><b>{{ title_new_releases }}</b></h4>
  </div>
</div>
<div class="row">
  <div class="col-12 pb-4 px-0">
    <div class="MultiCarousel" data-items="1,3,5,6" data-slide="1" id="MultiCarousel2"
         data-interval="1000">
      <div class="MultiCarousel-inner">

      {% include "cinema/includes/inc_index_product_slider.html" with product_list=new_releases_list %}

      </div>
      <button class="btn btn-primary leftLst"><</button>
      <button class="btn btn-primary rightLst">></button>
    </div>
  </div>
</div>

{% endblock main_content %}

cinema/templates/cinema/search_results.html
{% extends 'cinema/base.html' %}

{% block description %}{{ search_title }}"{{ query }}"{% endblock %}


{% block title %}{{ search_title }}"{{ query }}"{% endblock %}


{% block main_content %}

<div class="row">
  <div class="col-md-9">

    {% if product_list or film_list or person_list or news_list %}

      <h3 class="text-danger">{{ search_title }}"<b>{{ query }}</b>"</h3>

      {% if product_list %}

        <h4 class="pt-2">Movies on blu-ray found: {{ product_list.count }}</h4>

        {% for product in product_list %}

{% include "cinema/includes/inc_search.html" with object=product url_name='cinema:product-detail' image=product.film.poster.url title=product.film.title extra='Blu-ray' %}

        {% endfor %}

      {% endif %}

      {% if film_list %}

        <h4 class="pt-2">Movies found: {{ film_list.count }}</h4>

        {% for film in film_list %}

{% include "cinema/includes/inc_search.html" with object=film url_name='cinema:film-detail' image=film.poster.url title=film.title extra=film.year %}

        {% endfor %}

      {% endif %}

      {% if person_list %}

        <h4 class="pt-2">Cinema persons found: {{ person_list.count }}</h4>

        {% for person in person_list %}

{% include "cinema/includes/inc_search.html" with object=person url_name='cinema:movie-person-detail' image=person.avatar.url title=person.fullname extra=person.birthday|date:"Y" %}

        {% endfor %}

      {% endif %}

      {% if news_list %}

        <h4 class="pt-2">Cinema news found: {{ news_list.count }}</h4>

        {% for news in news_list %}

{% include "cinema/includes/inc_search.html" with object=news url_name='cinema:news-detail' image=news.news_feed_photo.url title=news.title extra=news.created_at|date:"j M Y H:i" %}

        {% endfor %}

      {% endif %}

    {% else %}

      <h3 class="text-danger">{{ no_results }}<b>"{{ query }}"</b></h3>

    {% endif %}

  </div>
  <div class="col-md-3">

  {% include "cinema/includes/inc_top_5_films.html" with title="Top 5 rated IMDb movies" top_5=imdb_top_5 criterion="imdb_top_5" %}
  {% include "cinema/includes/inc_top_5_films.html" with title="Top 5 most expensive movies" top_5=budget_top_5 criterion="budget_top_5" %}
  {% include "cinema/includes/inc_top_5_films.html" with title="Top 5 most USA grossing movies" top_5=usa_gross_top_5 criterion="usa_gross_top_5" %}
  {% include "cinema/includes/inc_top_5_films.html" with title="Top 5 most world grossing movies" top_5=world_gross_top_5 criterion="world_gross_top_5" %}

  </div>
</div>

{% endblock main_content %}