beta_project/urls.py
"""
beta_project URL Configuration.
"""

from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('cinema/', include('cinema.urls')),
    path('admin/', admin.site.urls),
    path('insane/', include('insane_app.urls')),
    path('rent-cars/', include('rent_cars.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

cinema/urls.py
from django.urls import path
from .apps import CinemaConfig
from .views import (ProductListView, ProductDetailView, NewsListView,
                    NewsDetailView, FilmDetailView, CinemaPersonDetailView,
                    FilmListView, TopRatedProductListView,
                    NewReleasesProductListView, CelebrityNewsListView,
                    TopRatedFilmListView, BudgetFilmListView,
                    UsaGrossFilmListView, WorldGrossFilmListView,
                    SearchResultsView, YearFilmListView, GenreFilmListView,
                    CountryFilmListView, LanguageFilmListView, MpaaFilmListView,
                    DistributorFilmListView, IndexListView)


app_name = CinemaConfig.name

urlpatterns = [
    path('', IndexListView.as_view(), name='index-list'),
    path('blu-ray/', ProductListView.as_view(), name='product-list'),
    path('film/', FilmListView.as_view(), name='film-list'),
    path('news/', NewsListView.as_view(), name='news-list'),
    path('search/', SearchResultsView.as_view(), name='search_results'),
    path('blu-ray/top-rated/', TopRatedProductListView.as_view(),
         name='top-rated-product-list'),
    path('blu-ray/new-releases/', NewReleasesProductListView.as_view(),
         name='new-releases-product-list'),
    path('film/top-rated/', TopRatedFilmListView.as_view(),
         name='top-rated-film-list'),
    path('film/budget/', BudgetFilmListView.as_view(),
         name='budget-film-list'),
    path('film/usa-gross/', UsaGrossFilmListView.as_view(),
         name='usa-gross-film-list'),
    path('film/world-gross/', WorldGrossFilmListView.as_view(),
         name='world-gross-film-list'),
    path('news/celebrity/', CelebrityNewsListView.as_view(),
         name='celebrity-news-list'),
    path('blu-ray/<int:pk>/', ProductDetailView.as_view(),
         name='product-detail'),
    path('film/<int:pk>/', FilmDetailView.as_view(),
         name='film-detail'),
    path('movie-person/<int:pk>/', CinemaPersonDetailView.as_view(),
         name='movie-person-detail'),
    path('news/<int:pk>/', NewsDetailView.as_view(),
         name='news-detail'),
    path('film/year/<int:year>/', YearFilmListView.as_view(),
         name='year-film-list'),
    path('film/genre/<str:genre>/', GenreFilmListView.as_view(),
         name='genre-film-list'),
    path('film/country/<str:country>/', CountryFilmListView.as_view(),
         name='country-film-list'),
    path('film/language/<str:language>/', LanguageFilmListView.as_view(),
         name='language-film-list'),
    path('film/mpaa/<int:pk>/', MpaaFilmListView.as_view(),
         name='mpaa-film-list'),
    path('film/distributor/<str:distributor>/',
         DistributorFilmListView.as_view(), name='distributor-film-list'),
]

insane_app/urls.py
from django.urls import path
from django.views.generic.base import RedirectView
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required

from insane_app import views

app_name = 'insane'

urlpatterns = [
    path('', views.StoryListView.as_view(), name='stories'),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='insane_accounts/login.html'), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('<int:pk>/', views.StoryDetailView.as_view(), name='story'),
    path('<int:pk>/like/', views.like_story, name='like_story'),
    path('create/', login_required(views.StoryCreateView.as_view()), name='create_story'),
    path('market/', views.ProductListView.as_view(), name='market'),
    path('market/<int:pk>/', views.ProductDetailView.as_view(), name='product'),
    path('market/create/', login_required(views.ProductCreateView.as_view()), name='create_product'),

    # path('', views.StoryListView.as_view(), name='stories'),
]

insane_app/models.py
from django.db import models
from django.db.models import F
from django.contrib.auth.models import User
from django.db.models.signals import pre_delete, post_save
from django.dispatch import receiver
from django.contrib.auth import get_user_model
from django.urls import reverse
from django.utils.html import escape

User = get_user_model()


class SanityRank(models.Model):
    name = models.CharField(unique=True, max_length=20)
    sanity_cap = models.PositiveIntegerField()

    def __str__(self):
        return self.name


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    _sanity = models.PositiveIntegerField(default=0)
    rank = models.ForeignKey(SanityRank, on_delete=models.PROTECT)

    @property
    def sanity(self):
        return self._sanity

    @sanity.setter
    def sanity(self, value):
        if value <= self.rank.sanity_cap:
            self._sanity = value
        else:
            self._sanity = self.rank.sanity_cap

    # FIXME: this code breaks the program for everyone else
    # @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            rank = SanityRank.objects.first()
            Profile.objects.create(user=instance, sanity=rank.sanity_cap, rank=rank)

    # FIXME: this code breaks the program for everyone else
    # @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        instance.profile.save()

    class Meta:
        ordering = ['user']
        db_table = 'insane_user'

    def __str__(self):
        return self.user.username


class UserGroup(models.Model):
    name = models.CharField(max_length=32)

    def get_new_admin(self):
        return self.members.first()

    members = models.ManyToManyField(
        User,
        related_name='user_group',
        through='Membership',
        through_fields = ('user_group', 'user')
    )
    dt_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    def add_member(self, new_user):
        Membership.objects.create(user = new_user, user_group=self)


class Membership(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    user_group = models.ForeignKey(UserGroup, on_delete=models.CASCADE)
    ROLES = (
        ('ad', 'admin'),
        ('mb', 'member'),
    )
    role = models.CharField(max_length=2, choices=ROLES)

    class Meta:
        unique_together = (('user', 'user_group'),)

    def __str__(self):
        return f'{self.user_group.name} - {self.user.username}[{self.get_role_display()}]'


class Story(models.Model):
    name = models.CharField(max_length=64)
    body = models.TextField(max_length=600)
    like_count = models.PositiveIntegerField(default=0, blank=True)
    dt_created = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True
    )

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('insane:story', args=[self.pk])


def get_story_image (instance, filename):
    return f"images/{instance.author.username}/{filename}"


class StoryImage(models.Model):
    image = models.ImageField(upload_to=get_story_image)
    product = models.ForeignKey(
        Story,
        related_name='image',
        on_delete=models.CASCADE
    )


class StoryLike(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    story = models.ForeignKey(Story, on_delete=models.CASCADE)

    class Meta:
        unique_together = (("user", "story"),)

    def __str__(self):
        return f"{self.user.username} likes {self.story.name}"


@receiver(post_save, sender=StoryLike)
def _story_like_save(sender, instance, **kwargs):
    Story.objects.filter(pk=instance.story.pk).update(like_count=F('like_count')+1)

@receiver(pre_delete, sender=StoryLike)
def _story_like_delete(sender, instance, **kwargs):
    Story.objects.filter(pk=instance.story.pk).update(like_count=F('like_count')-1)


class Category(models.Model):
    name = models.CharField(unique=True, max_length=20)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=64)
    description = models.TextField(max_length=500)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    story = models.ForeignKey(
        Story,
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )
    dt_created = models.DateTimeField(auto_now_add=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    categories = models.ManyToManyField(Category)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('insane:product', args=[self.pk])


# ProductImage
def get_product_image(instance, filename):
    return f"images/{instance.product.owner.username}/{filename}"


class ProductImage(models.Model):
    image = models.ImageField(upload_to=get_product_image)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    class Meta:
        unique_together = (('image', 'product'),)

    def __str__(self):
        return f"{self.product.name}, {self.image}"

    def image_tag(self):
        return f'<img src="/static/{self.image}"/>'

    image_tag.short_description = 'Image'
    image_tag.allow_tags = True

insane_app/views.py
from django.shortcuts import render, redirect
from django.utils import timezone
from django.http import HttpResponse
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required

User = get_user_model()

from insane_app.models import Story, Product, Category, StoryLike


class StoryListView(ListView):

    model = Story
    paginate_by = 20

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["now"] = timezone.now()
        return context


class StoryDetailView(DetailView):

    model = Story

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['now'] = timezone.now()

        try:
            StoryLike.objects.get(story__pk = kwargs['object'].pk, user = User.objects.first())    #self.request.user)
            context['liked'] = True
        except StoryLike.DoesNotExist:
            pass

        return context


def like_story(request, pk):
    object, created = StoryLike.objects.get_or_create(
        user=User.objects.first(),
        story=Story.objects.get(pk=pk)
    )

    if not created:
        object.delete()
    else:
        created = 1

    return HttpResponse(created)


class StoryCreateView(CreateView):
    model = Story
    fields = ('name', 'body')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        self.object.save()
        
        return redirect(self.get_success_url())


class ProductListView(ListView):

    model = Product
    paginate_by = 20

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["now"] = timezone.now()
        context["category_set"] = Category.objects.all().order_by('name')
        return context

    def get_queryset(self):
        categories_id = self.request.GET.getlist('categories')
        if categories_id:
            return self.model.objects.filter(categories__pk__in = categories_id)
        else:
            return self.model.objects.all()


class ProductDetailView(DetailView):

    model = Product

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['now'] = timezone.now()
        return context


class ProductCreateView(CreateView):

    model = Product
    fields = ('name', 'description', 'price')

    success_url = '/insane/market/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category_set'] = Category.objects.all()
        return context

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.owner = self.request.user
        categories = self.request.POST.getlist('categories', ())
        self.object.save()

        if categories:
            self.object.categories.set(Category.objects.filter(pk__in=categories))
        return redirect(self.get_success_url())

insane_app/templates/insane_app/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="/static/insane_app/css/master.css">
    <link rel="shortcut icon" type="image/png" href="{% static '/insane_app/images/favicon.ico' %}"/>
    <title>Insane Site</title>
  </head>

  <body>
    <nav class="navbar navbar-dark bg-black navbar-expand-md">
      <a class="navbar-brand" href="/insane/"> <img src="/static/insane_app/images/logo.jpg" alt="Insane" height="40"> </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'insane:stories' %}">Story</a>
          </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'insane:market' %}">Market</a>
            </li>
        </ul>
        <!-- <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form> -->
        <div class="navbar-nav">
          {% if user.is_authenticated %}
            <div class="progress m-3">
              <div class="progress-bar bg-info" role="progressbar" style="width: 100px;" aria-valuenow="{{user.profile.sanity}}" aria-valuemin="0" aria-valuemax="{{user.profile.rank.sanity_cap}}">{{user.profile.sanity}}</div>
            </div>
            <div class="nav-item m-1">
              <a class="nav-link" href="{% url 'insane:logout' %}">Logout</a>
            </div>
          {% else %}
            <div class="nav-item m-1">
              <a class="nav-link" href="{% url 'insane:login' %}">Login</a>
            </div>
          {% endif %}
        </div>
      </div>
    </nav>

    <div class="row m-0">
      <div class="col-md-2">
        {% block left_bar %}
        {% endblock %}
      </div>
      <div class="col-md-8">
        {% block body %}
        {% endblock %}
      </div>
      <div class="col-md-2">
        <div class="right_bar">
          {% block right_bar %}
          {% endblock %}
        </div>
      </div>
    </div>
  </body>
  <script src="/static/insane_app/javascript/jquery-3.4.1.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  <script src="https://kit.fontawesome.com/4699607bfc.js" crossorigin="anonymous"></script>
  <script src="/static/insane_app/javascript/my_ajax.js"></script>
</html>

insane_app/templates/insane_app/product_detail.html
{% extends 'insane_app/base.html' %}

{% block body %}
  <h3>{{object.name}}</h3>
  <div class="jumbotron">
    <div class="row">
      <div class="col-xl-3"></div>
       <div class="col-xl-6"><!--
        <div id="carousel" class="carousel slide" height="200" data-ride="carousel">
          <ol class="carousel-indicators">
            {% for image in object.productimage_set.all %}
              <li data-target="#carousel" data-slide-to="{{forloop.counter0}}" class="carousel-indicator{% if forloop.first %} active{% endif %}"></li>
            {% endfor %}
          </ol>
          <div class="carousel-inner">
            {% for image in object.productimage_set.all %}
              <div class="carousel-item{% if forloop.first %} active{% endif %}">
                <img class="d-block w-100" position="center" src="/media/{{image.image}}" alt="First slide">
              </div>
            {% endfor %}
          </div>
          <a class="carousel-control-prev" href="#carousel" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carousel" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
      </div> -->
      <img class="d-block m-4" position="center" height="200px" src="{% if object.productimage_set.count > 0 %}/media/{{object.productimage_set.first.image}}{% else %}/static/insane_app/images/default.jpg{% endif %}" alt="First slide">
      <div class="col-xl-3"></div>
    </div>
  </div>
  <p>Categories:
    {% for cat in object.categories.all %}
      {{cat.name}}{% if forloop.last %}.{% else %},{% endif %}
    {% empty %}
      no categories.
    {% endfor %}
  </p>
  <p>{{object.description}}</p>
  <p>Seller: {{object.owner.username}}</p>
  <p>Price: {{object.price}}</p>
{% endblock %}

insane_app/templates/insane_app/product_form.html
{% extends 'insane_app/base.html' %}

{% block body %}
  <div class="jumbotron">
    {{form.errors}}
    <form class="" method="post">
      {% csrf_token %}
      <div class="form-group">
        <label for="name">Product name</label>
        <input type="text" id="name" name="name" class="form-control">
      </div>
      <div class="form-group">
        <label for="description">Description</label>
        <textarea class="form-control" id="description" name="description" rows="3"></textarea>
      </div>
      <div class="form-group">
        <label for="price">Price</label>
        <input type="number" id="price" name="price" class="form-control">
      </div>
      <div class="form-group">
        <label for="categories">Categories</label>
        <select id="categories" name="categories" class="custom-select custom-select-sm" multiple>
          {% for category in category_set %}
            <option value="{{category.id}}">{{category}}</option>
          {% endfor %}
        </select>
      </div>
      <input type="submit" value="Create">
    </form>
  </div>
{% endblock %}

insane_app/templates/insane_app/product_list.html
{% extends 'insane_app/base.html' %}

{% block left_bar %}
  <form action="" method="get">
    <div class="card m-2">
      <div class="card-body">
        <h5 class="card-title">Category</h5>
          <select id="categories" name="categories" class="custom-select custom-select-sm" multiple>
            {% for category in category_set %}
              <option value="{{category.id}}">{{category}}</option>
            {% endfor %}
          </select>
          <input type="submit" class="btn btn-primary m-2" name="category_filter" value="Apply filter">
      </div>
    </div>
  </form>
  {% if user.is_authenticated %}
    <div class="card m-2">
      <div class="card-body">
        <a class="card-link" href="{% url 'insane:create_product' %}">Create new product</a>
      </div>
    </div>
  {% endif %}
{% endblock %}

{% block body %}
  <div class="container">
      <div class="row">
      {% for product in object_list %}
        <div class="col-sm-6 col-md-4 col-lg-4 d-flex">
          <div class="card flex-fill mb-4">
            <img class="img-fluid" height="auto" width="100%" src="
              {% if product.productimage_set.count %}
                /media/{{product.productimage_set.first.image}}
              {% else %}
                /static/insane_app/images/default.jpg
              {% endif %}
            " alt="">
            <div class="card-body">
              <a class="card-title card-link" href="{{ product.get_absolute_url }}">{{product.name}}</a>
              <p class="mb-0">price: ${{product.price}}</p>
            </div>
          </div>
        </div>
      {% empty %}
        <li class="list-group-item">No products yet</li>
      {% endfor %}
    </div>
  </div>
{% endblock %}

insane_app/templates/insane_app/story_detail.html
{% extends 'insane_app/base.html' %}

{% block body %}
  <div class="jumbotron">
    <h3>{{object.name}}</h3>
    <p>{{object.body}}</p>
    <p>
      <button data-storyid="{{ object.id }}" id="like"
        class="{% if liked %}fas{% else %}far{% endif %} fa-thumbs-up">
      </button>
      <var id="like_count">{{object.like_count}}</var>
    </p>
    <p>Date: {{object.dt_created}}</p>
    <p>Created by: {{object.author.username}}</p>
  </div>
{% endblock %}

insane_app/templates/insane_app/story_form.html
{% extends 'insane_app/base.html' %}

{% block body %}
  <div class="jumbotron">
    {{form.errors}}
    <form class="" method="post">
      {% csrf_token %}
      <div class="form-group">
        <label for="name">Story name</label>
        <input type="text" id="name" name="name" class="form-control">
      </div>
      <div class="form-group">
        <label for="body">Text</label>
        <textarea class="form-control" id="body" name="body" rows="7"></textarea>
      </div>
      <input type="submit" value="Create">
    </form>
  </div>
{% endblock %}

insane_app/templates/insane_app/story_list.html
{% extends 'insane_app/base.html' %}
{% load humanize %}

{% block left_bar %}
  {% if user.is_authenticated %}
    <div class="card m-2">
      <div class="card-body">
        <a class="card-link" href="{% url 'insane:create_story' %}">Create new story</a>
      </div>
    </div>
  {% endif %}
{% endblock %}

{% block body %}
  <div class="list-group list-group-flush">
    {% for story in object_list %}
      <div class="list-group-item list-group-item-light m-2">
        <div class="d-flex justify-content-between">
          <div>
            <a class="list-group-item-action" href="{{ story.get_absolute_url }}">
              {{story.name}}
            </a>
          </div>
          <div>
            author: {{story.author.username}}
          </div>
        </div>
        <a class="list-group-item-action" href="{{ story.get_absolute_url }}">
          {{story.body|truncatewords:20}}
        </a>
        <div class="d-flex justify-content-between">
          <div>
            <i class="far fa-thumbs-up"></i>{{story.like_count}}
          </div>
          <div>{{story.dt_created|naturaltime}}</div>
        </div>
      </div>
    {% empty %}
      <li>No stories yet</li>
    {% endfor %}
  </div>
{% endblock %}